version: "3.9"

services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    environment:
      # SERVER NODE CONFIG
      - SERVER_PORT = 2333
      - LAVALINK_SERVER_PASSWORD = youshallnotpass
    volumes:
      - ./Lavalink/application.yml:/opt/Lavalink/application.yml
      - ./Lavalink/plugins/:/opt/Lavalink/plugins/
    restart: on-failure

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    links:
      - lavalink
    env_file:
      - .env
